on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python script
        run: |
          python test.py > output.txt

      - name: Save output
        if: success()
        run: |
          mv output.txt $GITHUB_WORKSPACE/output.txt

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: $GITHUB_WORKSPACE/output.txt
